data:
  type: shareGPT
load:
  type: constant
  stages:
  - rate: 1
    duration: 30
api: 
  type: chat
server:
  type: vllm
  model_name: meta-llama/Llama-3.1-8B-Instruct
  base_url: http://0.0.0.0:8000
